# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: true

r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

matrix:
  include:
    - os: linux
      r: devel

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

script: 
  - |
    R CMD build .
    travis_wait 60 R CMD check --as-cran --use-valgrind sarima*.tar.gz
    
